- apps/closures-and-restrictions-map/src/components/App.tsx
- apps/closures-and-restrictions-map/src/components/Filters.tsx
- apps/closures-and-restrictions-map/src/components/Layers.tsx
- libs/react-mapbox/src/components/Cluster/Cluster.tsx
- nespravne prednastaveny filter, spolu s chybou vo filtry ze sa nedalo vypnut status sposobil ze sa nikdy nezobrazili data, kedze disorders hodnotu status  nemaju, preto boli vzdy odfiltrovane. Chyba je fixnuta tak ze som zmenil defaultny filter a fixol moznost vypnut tuto hodnotu
- trochu som zrefactoroval co mi vrazilo do oci v ramci closures mapy
> Disorders features displayed on map

- apps/closures-and-restrictions-map/src/components/App.tsx
- apps/closures-and-restrictions-map/src/components/Layers.tsx
- apps/closures-and-restrictions-map/src/utils/utils.ts
Odstranil som Opravy vykomentovanim kodu, ak ich bude treba vratit da sa len revertnut zmeny alebo odkomentovat zmeny, nechal som v kode aj comment s navodom ako to vratit
> Repair Layesrs Removed

- apps/closures-and-restrictions-map/src/components/App.tsx
- apps/closures-and-restrictions-map/src/components/Filters.tsx
- apps/closures-and-restrictions-map/src/components/Layers.tsx
- apps/closures-and-restrictions-map/src/components/TagFilter.tsx
- pridal som ten tooltip aj modal v ramci moznosti, musel som si zial skopcit instanciu komponenty TagFiltra. kedze som ju nechcel menit globalne v kniznici
- tie kniznicove komponenty nie su velmi stastne riesene, vela veci sa robi priamo v childoch a potom nemozes updatovat global stat v parente appky a na to aby som to urobil spravne by som musel toho prerabat ovela viac
- tooltip a modal som pripravil v parente aby sa dalo v buducnosti switchovat medzi viacerimi modalmi cez jeden globalny modal, bude sa menit len content modalu,
- nepotrebne tooltip a modal nestovane (nepouzivane som zmazal, ak tam v buducnosti bude treba spravi sa to cez parrent ako som to pripravil)
> Mp 108/tooltips

- libs/react-mapbox/src/components/Cluster/Cluster.tsx
- vratil som rekalkulaciu co sme zrusili, malo to negativny vplyv na rerenderovanie sa icon na mape a preblikavanie
- zmena bola spravena na branci PP-99, ostetne zmeny som nechal jak boli len rekalkulaciu som vratil aby sa korektne rerenderovali body
> Cluster Recalculaions Returned

- libs/react-mapbox/src/components/Cluster/Cluster.tsx
nastavil som rozpatie zobraziena bodov staticky pre cele zapadne Slovensko, kedze tam bol nejaky bug a nenacitavalo sa rozpatie spravne na mobile a tablete
> Cluster - bbox changed to static

- apps/closures-and-restrictions-map/src/components/App.tsx
- apps/cvicko-map/src/components/App.tsx
- apps/drinking-fountains-map/src/components/App.tsx
- apps/greenary-care-map/src/components/App.tsx
- apps/homeless-people-help-map/src/components/App.tsx
- apps/non-residential-premises-map/src/components/App.tsx
- apps/paas-map/src/components/App.tsx
- apps/planting-map/src/components/App.tsx
- apps/sport-grounds-map/src/components/App.tsx
- libs/react-mapbox/src/components/Mapbox/Mapbox.tsx
Na cvicko mapach som nechal pitch -  3D sphere povoleny k voli animaciam
> Mobile rotating, fixed, 3D sphere disabled

- apps/closures-and-restrictions-map/src/components/App.tsx
po code revius sa doplnili dependencies do useeffectu, toto rozbilo spravanie appky ktore som otestoval a bolo funkcne, musel som spravit workeround aby som nemusel prerabat komplet pol appky a aby som korektne nastavil aj dependencies. Teraz som to otestoval a funguje to ako ma.
> fixed issue on iframe

- apps/closures-and-restrictions-map/src/components/Layers.tsx
- neda sa vypnut posledny layer z filtra
- odfiltrovane neexistujuce layers zo sidebaru aby to sedelo s default filtrom
> Layer Filter Updated

- apps/greenary-care-map/src/components/App.tsx
- apps/non-residential-premises-map/src/components/App.tsx
- libs/react-maps-ui/package.json
- libs/react-maps-ui/src/components/Popover.tsx
- libs/react-maps-ui/src/components/PopoverArrow.tsx
- libs/react-maps/src/components/ViewportController/LegendButton.tsx
- depricated lib replaced,
- position of legend was set on load before parent is rendered, workeround by timeout, same issue in other map was fixed.
> Legend fixed

- apps/homeless-people-help-map/src/components/Detail/DetailWebRow.tsx
- apps/homeless-people-help-map/src/components/Detail/MainDetail.tsx
- apps/homeless-people-help-map/src/components/Detail/OtherServiceDetail.tsx
- apps/homeless-people-help-map/src/components/Detail/TerrainServiceDetail.tsx
Musel som vytvorit prepouzitelny component, pretoze su 3 rozne detaily s web linkou a bol tam pouzivany nejaky globalny komponent DataDisplay z kniznice ktory je v podstate nepouzitelny na nic ine a nechcel som ho prerabat kedze sa asi pouziva v inych mapach.
> Web links changed

- libs/react-maps/package.json
- libs/react-maps/src/components/Map/Map.tsx
Instead changing breakpoints, i added device detection, so in browser should be modal not displayed at all
> Mobile detector added

- apps/sport-grounds-map/src/translations/sk.ts
From "Mapa športu v Bratislave" to "Kúpaliská a Cvičko"
> Update map title

- apps/sport-grounds-map/src/utils/utils.ts
> Icon change for Areál zdravia Zlaté piesky, from pool to water

- apps/non-residential-premises-map/src/components/App.tsx
- apps/non-residential-premises-map/src/utils/utils.ts
Pridal som novy link na data, treba fixnut data aby atribut orientacna cena za rok bola cislo ako pred tym inak sa nezobrazia data k voli filtru
> New Data Source Added

- apps/non-residential-premises-map/src/components/App.tsx
- apps/non-residential-premises-map/src/components/Detail/DetailDataDisplay.tsx
- apps/non-residential-premises-map/src/components/Detail/SingleFeatureDetail.tsx
- apps/non-residential-premises-map/src/utils/utils.ts
pridal som aj nejake korekcie co chcel Kubo v detaile
> Mp 185/iframe settings nonresidential

- apps/non-residential-premises-map/src/utils/colors.ts
> Update district border colors.ts

- apps/non-residential-premises-map/src/components/Detail/SingleFeatureDetail.tsx
Problem bol v tom, ze pri priradeni "image" sa nekontrolovalo, ci existuju featureAttachments images, preto sa pri neexistujucom feature.properties.picture priradil defaultny placeholder
> Fixed showing the image in the detail modal

- apps/homeless-people-help-map/src/components/App.tsx
- apps/homeless-people-help-map/src/components/Detail/OtherServiceDetail.tsx
- apps/homeless-people-help-map/src/components/Filters.tsx
- apps/homeless-people-help-map/src/components/Legend.tsx
- apps/homeless-people-help-map/src/components/Marker.tsx
- apps/homeless-people-help-map/src/translations/en.ts
- apps/homeless-people-help-map/src/translations/sk.ts
- apps/homeless-people-help-map/src/utils/colors.ts
- layer notabene removed
- filter notabene removed
- legend notabene item removed
- color notabene removed
- translations notabene removed
> [#173] remove notabene filter and layer

- apps/homeless-people-help-map/src/assets/icons/layers/terrain-service.svg
- apps/homeless-people-help-map/src/components/Legend.tsx
- apps/homeless-people-help-map/src/translations/en.ts
- apps/homeless-people-help-map/src/translations/sk.ts
- add terrainservice to Legend
> [bratislava/private-maps#16] add terrainservice to Legend

- apps/homeless-people-help-map/src/translations/en.ts
- apps/homeless-people-help-map/src/translations/sk.ts
Add subject to mail for slovak and english.
> [#167] add subject to mail

- apps/homeless-people-help-map/src/components/Detail/TerrainServiceDetail.tsx
- apps/homeless-people-help-map/src/components/Detail/TerrainServiceMultipleWrapper.tsx
- apps/homeless-people-help-map/src/components/Detail/index.tsx
- apps/homeless-people-help-map/src/utils/types.ts
- fix missing null type
- refactor
> [#169] fix types homeless-people-help-map

- apps/homeless-people-help-map/en.html
- apps/homeless-people-help-map/sk.html
- apps/homeless-people-help-map/src/translations/en.ts
- apps/homeless-people-help-map/src/translations/sk.ts
> [#169] change name of homeless map

- apps/closures-and-restrictions-map/src/utils/utils.ts
Add custom name for contractor and investor in special cases of closures map.
> [#216] custom name for investor and contractor closures map

- apps/closures-and-restrictions-map/src/components/App.tsx
- apps/cvicko-map/src/components/App.tsx
- apps/paas-map/src/components/App.tsx
- remove condition preventing showing map without data
- formatting
- removing now unnecessary calling through nest-proxy -> now we can directly call geoportal
> #223 fix showing map

- apps/homeless-people-help-map/src/translations/en.ts
> Update people in need text en.ts

- apps/paas-map/src/components/App.tsx
- use proxy for request on geoportal
> change data address to request through proxy

- apps/homeless-people-help-map/src/utils/urls.ts
- add nest proxy to PUBLIC_TOILETS_URL (homeless-people-help-map
> add nest proxy to PUBLIC_TOILETS_URL (homeless-people-help-map)
